<?php 
namespace app\admin\validate;

use think\Validate;

class Permission extends Validate
{
	protected $rule = [
		'permission_see'		=>'number',
		'permission_c'			=>'number',
		'permission_u'			=>'number',
		'permission_d'			=>'number',
		'permission_level_id'	=>'number',
		'admin_see'				=>'number',
		'admin_c'				=>'number',
		'admin_u'				=>'number',
		'admin_d'				=>'number',
		'admin_level_id'		=>'number',
		'level_see'				=>'number',
		'level_c'				=>'number',
		'level_u'				=>'number',
		'level_d'				=>'number',
		'level_level_id'		=>'number',
		'article_see'			=>'number',
		'article_c'				=>'number',
		'article_u'				=>'number',
		'article_d'				=>'number',
		'column_see'			=>'number',
		'column_c'				=>'number',
		'column_u'				=>'number',
		'column_d'				=>'number',
		'tag_see'				=>'number',
		'tag_c'					=>'number',
		'tag_u'					=>'number',
		'tag_d'					=>'number',
		'notice_see'			=>'number',
		'notice_c'				=>'number',
		'notice_u'				=>'number',
		'notice_d'				=>'number',
		'link_see'				=>'number',
		'link_c'				=>'number',
		'link_u'				=>'number',
		'link_d'				=>'number',
		'sentence_see'			=>'number',
		'sentence_c'			=>'number',
		'sentence_u'			=>'number',
		'sentence_d'			=>'number',
		'comment_see'			=>'number',
		'comment_u'				=>'number',
		'name'					=>'require|chsAlphaNum|length:1,20',
		'__token__'				=>'token',
	];

	protected $message = [
		'__token__.token'					=>'不能重复提交！',
		'name.require'						=>'名称不能为空！',
		'name.chsAlphaNum'					=>'名称只能是汉字、数字及字母组成！',
		'name.length'						=>'名称的长度只能在1到20之间！',
		'permission_u.number'				=>'非法操作！',
		'permission_c.number'				=>'非法操作！',
		'permission_d.number'				=>'非法操作！',
		'permission_see.number'				=>'非法操作！',
		'permission_level_id.number'		=>'非法操作！',
		'admin_see.number'					=>'非法操作！',
		'admin_c.number'					=>'非法操作！',
		'admin_u.number'					=>'非法操作！',
		'admin_d.number'					=>'非法操作！',
		'admin_level_id.number'				=>'非法操作！',
		'level_see.number'					=>'非法操作！',
		'level_c.number'					=>'非法操作！',
		'level_u.number'					=>'非法操作！',
		'level_d.number'					=>'非法操作！',
		'level_level_id.number'				=>'非法操作！',
		'article_see.number'				=>'非法操作！',
		'article_c.number'					=>'非法操作！',
		'article_u.number'					=>'非法操作！',
		'article_d.number'					=>'非法操作！',
		'column_see.number'					=>'非法操作！',
		'column_c.number'					=>'非法操作！',
		'column_u.number'					=>'非法操作！',
		'column_d.number'					=>'非法操作！',
		'tag_see.number'					=>'非法操作！',
		'tag_c.number'						=>'非法操作！',
		'tag_u.number'						=>'非法操作！',
		'tag_d.number'						=>'非法操作！',
		'notice_see.number'					=>'非法操作！',
		'notice_c.number'					=>'非法操作！',
		'notice_u.number'					=>'非法操作！',
		'notice_d.number'					=>'非法操作！',
		'link_see.number'					=>'非法操作！',
		'link_c.number'						=>'非法操作！',
		'link_u.number'						=>'非法操作！',
		'link_d.number'						=>'非法操作！',
		'sentence_see.number'				=>'非法操作！',
		'sentence_c.number'					=>'非法操作！',
		'sentence_u.number'					=>'非法操作！',
		'sentence_d.number'					=>'非法操作！',
		'comment_see.number'				=>'非法操作！',
		'comment_u.number'					=>'非法操作！',
	];
}