<?php 
namespace app\admin\controller;

use think\Controller;
use app\admin\model\Admin as AdminModel;
use think\Session;
use captcha\GeetestLib;
//登陆控制器
class Login extends Controller
{

    public $config = [
        'geetest_id' => '582e201347b4dffbdb28f4984c1ca677', //填写获取到的id
        'geetest_key' => '6a1b68a72fa4753c410c0df9eb1740dd', //填写获取到的key
    ];
    public $param = [];

	//显示登陆页面

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub



//        $this->config = Config::get('captcha.config');
        $this->param = [
            "user_id" => "captcha", # 这个是用户的标识，或者说是给极验服务器区分的标识，如果你项目没有预先设置，可以先这样设置：
            "client_type" => "web", #web:电脑上的浏览器；h5:手机上的浏览器，包括移动应用内完全内置的web_view；native：通过原生SDK植入APP应用的方式
            "ip_address" => "127.0.0.1" # 请在此处传输用户请求验证时所携带的IP
        ];
    }

    public function index()
	{
        //验证是否已经登陆
        if ($res = Session::get('admin.username')) {
            $this->redirect('Index/index');
        }
		return $this->fetch();
	}

	//退出登录
	public function quit()
	{
		@session_start();
		unset($_SESSION['admin']);
		$this->redirect('Login/index');
	}

    //极验使用
    public function StartCaptchaServlet() {
        $GtSdk = new GeetestLib($this->config['geetest_id'], $this->config['geetest_key']);
        $status = $GtSdk->pre_process($this->param, 1);
        Session::set('gtserver', $status);
        Session::set('user_id', 1);
        echo $GtSdk->get_response_str();
    }

	//登陆验证
    public function check() {

        if($param = input('post.')) {
            //极验使用
            $GtSdk = new GeetestLib($this->config['geetest_id'], $this->config['geetest_key']);
            $param = input('post.');
            $jiyan = 0;
            if (Session::get('gtserver') == 1) {
                $jiyan = $GtSdk->success_validate($param['geetest_challenge'], $param['geetest_validate'], $param['geetest_seccode'], $this->param);
            } else { //宕机
                $jiyan = $GtSdk->fail_validate($param['geetest_challenge'], $param['geetest_validate'], $param['geetest_seccode']);
            }
            if ($jiyan === 0) {
                $this->error('请先完成拼图认证');
            }

            //账号密码验证
            $adminModel = new AdminModel();
            $res = $adminModel->check($param);
            if ($res === 1) {
                $this->error('重复提交');
            }elseif ($res === 2) {
                $this->error('账号或密码错误');
            } elseif ($res === 3) {
                @session_start();
                $_SESSION['admin'] = $adminModel->where('username', $param['username'])->field('id,username,dpic')->find();
                $this->redirect('Index/index');
            }
        }else{
            $this->redirect('Login/index');
        }
    }
}
